
import Head from 'next/head';
import HomePage from "./home/content";


const Home = () => {
  return (
    <div className="">
      <Head>
        <title>Portfolio-Nawel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <HomePage />
    </div>
  )
}

export default Home;